*** Starting uWSGI 2.0.17.1 (64bit) on [Sat Sep 22 16:11:59 2018] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.2) on 22 September 2018 08:09:16
os: Darwin-17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
nodename: zzdedeMacBook-Pro.local
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /Users/zzde/Code/medicine
writing pidfile to ./uwsgi/uwsgi.pid
detected binary path: /Users/zzde/Code/medicine/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to .
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 10240
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Python main interpreter initialized at 0x7fd9c7806200
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 702380 bytes (685 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x7fd9c7806200 pid: 24840 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 24840)
spawned uWSGI worker 1 (pid: 24857, cores: 2)
Python auto-reloader enabled
spawned uWSGI worker 2 (pid: 24858, cores: 2)
spawned uWSGI worker 3 (pid: 24859, cores: 2)
spawned uWSGI worker 4 (pid: 24860, cores: 2)
*** Stats server enabled on ./uwsgi/uwsgi.status fd: 23 ***
SIGINT/SIGQUIT received...killing workers...
worker 4 buried after 1 seconds
worker 3 buried after 1 seconds
worker 2 buried after 1 seconds
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket ./uwsgi/uwsgi.status (stats) removed.
*** Starting uWSGI 2.0.17.1 (64bit) on [Sat Sep 22 16:56:37 2018] ***
compiled with version: 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.10.44.2) on 22 September 2018 08:11:52
os: Darwin-17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64
nodename: zzdedeMacBook-Pro.local
machine: x86_64
clock source: unix
detected number of CPU cores: 4
current working directory: /Users/zzde/Code/medicine
writing pidfile to ./uwsgi/uwsgi.pid
detected binary path: /Library/Frameworks/Python.framework/Versions/3.6/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to .
your processes number limit is 709
your memory page size is 4096 bytes
detected max file descriptor number: 10240
lock engine: OSX spinlocks
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :8001 fd 3
Python version: 3.6.6 (v3.6.6:4cf1f54eb7, Jun 26 2018, 19:50:54)  [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
Python main interpreter initialized at 0x7feb68001a00
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 702380 bytes (685 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
Traceback (most recent call last):
  File "./medicine/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 136, in __init__
    self.load_middleware()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/core/handlers/base.py", line 34, in load_middleware
    middleware = import_string(middleware_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "./user/auth.py", line 7, in <module>
    from .tools import *
  File "./user/tools.py", line 5, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 26283)
spawned uWSGI worker 1 (pid: 26293, cores: 2)
spawned uWSGI worker 2 (pid: 26294, cores: 2)
spawned uWSGI worker 3 (pid: 26295, cores: 2)
spawned uWSGI worker 4 (pid: 26296, cores: 2)
*** Stats server enabled on ./uwsgi/uwsgi.status fd: 23 ***
Python auto-reloader enabled
